azure_resource_group = "downstream-rg"    ### Provide the Resource Group Name in which AKS Cluster is existed.
azure_region = ["East US", "East US 2", "Central India", "Central US"]
rancher2_access_key = "token-XXXXX"
rancher2_secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
azure_client_id = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
azure_client_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
azure_subscription_id = "5XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
azure_aks_cluster = "downstream-cluster"  ### Provide the Name of the AKS Cluster, the same name will be displayed after importing into Rancher UI.
delaysec = 2
